#Extrapolating gamma and temperature coefficient values from single set of data generated by temperature dependent model

library(mcstate)
library(odin.dust)

# SIR model - temperature dependent beta with gamma and temperature coefficient input as log values to aid fitting
sir <- odin.dust::odin_dust("testing_sparse_data/sir_temp_new.R")

# load example data generated by same model
data_example <- readRDS(file = "testing_sparse_data/example_data.Rds")

# load example case data
df_tidy <- data_example$example_data_single
t_pts=length(df_tidy$day)

# Get parameters used to generate data
gen_params <- data_example$parameters_single

# turn into data object
data <- particle_filter_data(df_tidy, 
                                      time = "day",
                                      rate = 1,
                                      initial_time = 0)

# sourcing the compare function which defines what to fit to and how- here it is assuming a poisson likelihood
# sourcing the index function- this tells mcstate which model and data outputs to look for
source("sir_temp_example/compare_sir_temp.R") # observation process could also appear here
source("sir_temp_example/index_sir_temp.R")

#Create particle filter
filter <- particle_filter$new(data, 
                              model = sir, 
                              n_particles=100,
                              compare = compare, 
                              index = index)

#Set up prior probability distributions and initial, minimum and maximum values for fitted parameters
priors <- list(pmcmc_parameter("log_gamma", initial = log(0.25), min = log(0.05), max = log(0.5), prior = function(p)
                               pnorm(p,mean=log(0.1),sd=1,log=TRUE)),
               pmcmc_parameter("log_temp_scale", initial = log(1.5e-5), min = log(1.0e-5), max = log(1.0e-3), prior = function(p)
                               pnorm(p,mean=log(1.0e-4),sd=1,log=TRUE)))

#Transform function for other parameters
make_transform <- function(I0,S0,Temp) {
  function(theta) {
    c(list(I0 = I0, S0 = S0, Temp = Temp), 
      as.list(theta))
  }
}

#Create matrix of covariance values for varied parameters
vcv <- (1e-1) ^ 2 * diag(2) / 2 # this is for the proposal distribution

#Set up all parameters for MCMC run
mcmc_pars <- pmcmc_parameters$new(priors, vcv, 
                                  transform=make_transform(I0 = gen_params$I0, S0 = gen_params$S0, Temp=gen_params$Temp)) 

#MCMC run
n_steps_in <- 2e3
control <- pmcmc_control(n_steps = n_steps_in, progress = TRUE, save_trajectories=TRUE)
samples <- pmcmc(mcmc_pars, filter, control = control)

#Plot posterior likelihood progression over steps
matplot(x=c(1:nrow(samples$probabilities)),y=samples$probabilities[,3],type="l",xlab="Iteration",ylab="Posterior likelihood")
title("Posterior likelihood progression")

burnin=0.5*n_steps_in #Value from which to begin taking trajectory case values to plot

#Plot post-burn-in modelled values compared with observed data
matplot(x=c(1:(t_pts+1)),y=t(samples$trajectories$state["cases",c(burnin:n_steps_in),]),type="p",pch=16,cex=0.25,col=1,
        ylim=c(0,max(c(samples$trajectories$state["cases",c(burnin:n_steps_in),],df_tidy$cases))),xlab="Day",ylab="Cases")
matplot(x=df_tidy$day,y=df_tidy$cases,type="l",lwd=2.0,col=2,add=TRUE)
legend("topleft",c("Modelled", "Observed"),col=c(1,2),pch=c(16,NA),lty=c(0,1))

parameters_out=list(log_gamma=samples$pars[,1],log_temp_scale=samples$pars[,2])

matplot(x=c(1:n_steps_in),y=parameters_out$log_gamma,type="l",col=1,xlab="Iteration",ylab="Value",
        ylim=range(c(parameters_out$log_gamma,gen_params$log_gamma,parameters_out$log_temp_scale,gen_params$log_temp_scale)))
matplot(x=c(1,n_steps_in),y=rep(gen_params$log_gamma,2),type="l",lwd=2.0,lty=2,col=1,add=TRUE)
matplot(x=c(1:n_steps_in),y=parameters_out$log_temp_scale,type="l",col=2,add=TRUE)
matplot(x=c(1,n_steps_in),y=rep(gen_params$log_temp_scale,2),type="l",lwd=2.0,lty=2,col=2,add=TRUE)
legend("right",c("Log gamma", "Log gamma (input)", "Log temperature coefficient", 
                 "Log temperature coefficient (input"),lty=c(1,2,1,2),col=c(1,1,2,2))
