sir <- odin2::odin({
  N <- parameter(1000)
  I0 <- parameter(10)
  beta <- parameter(0.4)
  gamma <- parameter(0.1)
  p_reporting <- parameter(1.0)
  
  p_SI <- 1 - exp(-beta * I / N * dt)
  p_IR <- 1 - exp(-gamma * dt)
  n_SI <- Binomial(S, p_SI)
  n_IR <- Binomial(I, p_IR)
  
  update(S) <- S - n_SI
  update(I) <- I + n_SI - n_IR
  update(R) <- R + n_IR
  update(incidence) <- n_SI
  update(incidence_observed) <- Binomial(n_SI, p_reporting) + 0.01
  
  initial(S) <- N - I0
  initial(I) <- I0
  initial(R) <- 0
  initial(incidence, zero_every = 1) <- 0
  initial(incidence_observed, zero_every = 1) <- 0
  
  cases <- data()
  cases ~ Poisson(incidence_observed)
})

p_reporting_fixed = 0.5

#Load sample data generated by model and adjust for reporting rate
data = read.csv(file = "new_packages_demo/example_data.csv", header=TRUE)
data$cases_total=data$cases
data$cases = rbinom(nrow(data),data$cases_total,p_reporting_fixed)

pars <- list(N = 1000, I0 = 10, beta = 0.2, gamma = 0.1, p_reporting = p_reporting_fixed)
sys <- dust2::dust_system_create(generator = sir, pars = pars, time = 0, dt = 1, deterministic = FALSE, 
                                 n_particles = 1, n_threads = 1, seed = 1, preserve_particle_dimension = TRUE)
t <- seq(1, nrow(data), by = 1) 
dust2::dust_system_set_state_initial(sys = sys)
y <- dust2::dust_system_simulate(sys = sys, times = t)

results <- dust2::dust_unpack_state(obj = sys, state = y)

matplot(x = t, y = t(results$S), type="p", pch = 16, col=2, xlab = "Day", ylab = "", ylim=c(0, pars$N))
matplot(x = t, y = t(results$I), type="p", pch = 16, col=3, add=TRUE)
matplot(x = t, y = t(results$R), type="p", pch = 16, col=4, add=TRUE)
legend("topright",c("S","I","R"),pch=c(16,16,16),col=c(2,3,4))

matplot(x = t, y = t(results$incidence_observed), type="p", pch = 16, col=1, xlab = "Day", ylab= "Incidence (observed)")

index = dust2::dust_unpack_index(obj = sys)
S = y[index$S,,]
I = y[index$I,,]
R = y[index$R,,]
incidence_observed = y[index$incidence_observed,,]

filter <- dust2::dust_filter_create(generator = sir, data = data, time_start = 0, n_particles = 20)
packer <- monty::monty_packer(scalar = c("beta","gamma"), array = NULL, 
                              fixed = list(N = 1000, I0 = 10, p_reporting = p_reporting_fixed))
prior <- monty::monty_dsl({
  beta ~ Uniform(min=0.05,max=0.5)
  gamma ~ Uniform(min=0.05,max=0.5)
})
likelihood <- dust2::dust_likelihood_monty(obj = filter, packer = packer)
posterior <- likelihood + prior
vcv <- matrix(c(0.01, 0.005, 0.005, 0.01), 2, 2)
sampler <- monty::monty_sampler_random_walk(vcv = vcv)
n_chains=1
n_iterations=500

samples <- monty::monty_sample(model = posterior,sample = sampler,n_steps = n_iterations,
                               initial = array(rep(c(0.05, 0.25), n_chains), dim=c(2, n_chains)), n_chains = n_chains)

# Plot posterior over iterations
matplot(x = c(1:n_iterations), y = samples$density[,1], type = "l", xlab = "Iteration", ylab = "Posterior")

# Plot parameter estimates over iterations (solid lines) with true values used to generate example data (dotted lines)
matplot(x = c(1:n_iterations), y = samples$pars[1,,1], type = "l", col = 2, xlab = "Iteration", ylab = "", ylim = c(0, 0.5))
matplot(x = c(1:n_iterations), y = samples$pars[2,,1], type = "l", col = 3, add = TRUE)
matplot(x = c(1, n_iterations), y = rep(0.2, 2), type = "l", col = 2, lty = 2, add = TRUE)
matplot(x = c(1, n_iterations), y = rep(0.1, 2), type = "l", col = 3, lty = 2, add = TRUE)
legend("topright", c("beta", "gamma"), lty=c(1,1), col=c(2,3))

# Calculate incidence using final estimated values and compare with example data
pars2 <- list(N = 1000, I0 = 10, beta = as.numeric(samples$pars[1,n_iterations,1]), 
              gamma = as.numeric(samples$pars[2,n_iterations,1]))
sys2 <- dust2::dust_system_create(generator = sir, pars = pars2, time = 0, dt = 1, deterministic = FALSE, 
                                  n_particles = 10, n_threads = 1, seed = 1, preserve_particle_dimension = TRUE)
index2 = dust2::dust_unpack_index(sys2)
dust2::dust_system_set_state_initial(sys2)
y2 <- dust2::dust_system_simulate(sys = sys2, times = data$time)

matplot(x = data$time, y = data$cases, type="l", col=1, xlab = "Day", ylab= "Incidence (observed)")
matplot(x = data$time, y = t(y2[index2$incidence_observed,,]), type="p", pch = 1, col=2, add=TRUE)
legend("topright",c("Original data","Data from estimated parameters"),col=c(1,2),lty=c(1,0),pch=c(NA,1))